apiVersion: ENC[AES256_GCM,data:E6A=,iv:RtiNomvKWyrRAi338wPwGHyVt+bbMHmskGJyRS6z2XQ=,tag:4yDmA8T+3c07J80LKWvcgg==,type:str]
kind: ENC[AES256_GCM,data:4ydPMv2U,iv:w10qYXkTnsE0Lu13Mh5cnXIIVqXOrkn9iOjWPDVzSIc=,tag:L4I2JrPxZua9YmvaeMI2xA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:yohGTvp8NwcUOFW0puFk/vGusw==,iv:5xCJEkK1oNcT9DWnJy/zJZMIc2pp/smr5kXvIav7bhI=,tag:R7k7qaD7ievE+8HKsE6mSg==,type:str]
    namespace: ENC[AES256_GCM,data:Xd6fSXUXFqcbpu/I,iv:+IfDitoUqOmHm3sSJuvPmaAv7krAa0jNffE64S6AUcE=,tag:43/Up9Wr3BFZRCl9vHnRRg==,type:str]
type: ENC[AES256_GCM,data:6hNp3AJb,iv:nzx2j2pD5RGSh+lSW2ojl0jVPEHL6AQlIwD78Ifh6tU=,tag:LmJEh34J6sZufxIKig5h9Q==,type:str]
stringData:
    token: ENC[AES256_GCM,data:G/JIeDdFK95BmNX721KoRK8C11L82uRpmg/j9I0nlwwwPw+CFcXKow==,iv:DJkruaDHWVBs5Dc0+K17zb6+ncdWKa8nqyhg/GVgVQA=,tag:radbJARiEg0IX+sXY10anA==,type:str]
sops:
    age:
        - recipient: age1fwe5ta3ey6mzz35t9tupd9a7wpcx5zch9x886hg53vll0ev77g6st4wwc6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UjRKNGQ0TjZEcjJOWFBY
            T1p4SU1sN2hKY2puUHplcHc0cEJQQVdsQmpRCnlhTDhSZXZSWXVVaE5meXRWSkxa
            ZGRYTVpqRTBKMDQ1K1AwVkVsNFpvZlEKLS0tIHoxV05DNHlsa3c1NXZ3bmJCUWhq
            eVpUeVNXSkhjSTFmeW9DQ29UNHlibXMK7x62JP9doHAc6IWtigjK0LeZVvYq3nJ3
            eRFGPZOWNDq3uqC/u/pKgHk/CRufjgcmeQZZD39cQPAYwOAVjD/tZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T17:54:05Z"
    mac: ENC[AES256_GCM,data:nAIQhtcfnPD8BVP7ikMUsHiv6wCT4UdmfEuWHU1VL7w3dLP0rlWc7RFRPjA0UfcI6WajqbZC0CevheXRKAExmUGyZ2QS6W5bN3g4szb4i1criLPosk0WDrw87WHGecAXcQAE5dax2jljQrHcieHR6KwsSbQ6Wyqlctyryrsetl0=,iv:XTCSQHwjZcT9iHDYGGohimfO1UKf0sZSpG5QbDeTBBU=,tag:+R+5IhyIzCYADUVnWoRQQA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
