---
# Homarr IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homarr
  namespace: homelab
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`homarr.lab.jamilshaikh.in`)
      kind: Rule
      services:
        - name: homarr
          port: 7575
  tls:
    secretName: wildcard-lab-tls  # Replicated wildcard certificate
