---
# Prometheus IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prometheus.lab.jamilshaikh.in`)
      kind: Rule
      services:
        - name: prometheus-stack-kube-prom-prometheus
          port: 9090
  tls:
    secretName: prometheus-tls-cert
---
# TLS Certificate for Prometheus
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-tls-cert
  namespace: monitoring
spec:
  secretName: prometheus-tls-cert
  issuerRef:
    name: homelab-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: prometheus.lab.jamilshaikh.in
  dnsNames:
    - prometheus.lab.jamilshaikh.in
  privateKey:
    algorithm: RSA
    size: 2048
  duration: 2160h
  renewBefore: 360h
