apiVersion: ENC[AES256_GCM,data:IrA=,iv:6qRIcwbuaYgY317QlwxUJxrS3M8c0WjyOjeEZchdPHI=,tag:apaUMlNLI91g6C3oDfOvFg==,type:str]
kind: ENC[AES256_GCM,data:QgswvjNj,iv:0L/VLEz/SfqWSHV9z4oX1TkDK6nJV0YDTpvK/gL356s=,tag:rp4uC3woe1B33Y2xNiiMoQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:f/WpR08S8/w/xVgzdwfRHRECW7DrILZN,iv:nOWm1BDc0xrw9sq95YnjqxAg+gWaNL9ZZJ1r8ICp+BU=,tag:95Kw7OEo0gRtlwTrqNvwMA==,type:str]
    namespace: ENC[AES256_GCM,data:PNEMfp0lmN0/oaU=,iv:+fseVKyCo4kGWv901JJpZJHb51eHhhH44BnQK+vwyr4=,tag:qYwj5loXrk8PnQc2QRa0zg==,type:str]
type: ENC[AES256_GCM,data:QAxE8PEQ,iv:0ftn76SQOIjjI+1gjF2AWtdUJNOQM3M0mm4OuGk29xQ=,tag:pUxsv9KHwHZJGDhO/ov3wQ==,type:str]
stringData:
    token: ENC[AES256_GCM,data:O+0k/ebIwUUHL/xlKHWsPoCV4cLjw7rV2nafTxkq2qAD3lRkIHOvNOj5HWqlXXRmVcJUepYDnBgI2bsEuiWGB7Xi7Sum0QZO2LzJD8v1Wxj9QdNWMmkUC2tHRIPmt3hSdCqVx3HN2h/jxJzZM9MTPsVw0xBiTFldOk5IKdqFjP6mGZ2lyYIlBVLom302ljJytacuJK7ePL8RIxiBoZxeykDuxQiNDJOXTZClyW9cq11z5M7YzVjUSA==,iv:s9evZllbiR4TdfMz/czQbY4juFg+PqaszuqhNJUfTiY=,tag:7QsCOs72R1NUiIv9vCxglA==,type:str]
sops:
    age:
        - recipient: age1fwe5ta3ey6mzz35t9tupd9a7wpcx5zch9x886hg53vll0ev77g6st4wwc6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bWFDbmRjV0FHSmVvVW5z
            dm1aNkRLdWhOMkxTWHdyNG44TjFhTWhhb1J3CklPMzY3bnZjQlpTejE3OW5SdUxZ
            RjZ3Y2VjK2VMSDZndTRNejBBMVBzcncKLS0tIDRnOWx3MVhiZkY0bm9BK04wTk1s
            MzJTNVErZEZMenlZMU5kVnQ1cjh6bmcKDDS5Ifv2jjWf552f92FaWFBIqIRPmAlq
            4yY6bQk+eD2IknhQPKOtLB5/y9Htha0CoCgA7a6dg8ApWvnFNeHEFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T17:40:20Z"
    mac: ENC[AES256_GCM,data:IIS2RKE5qNs2pdpC17AecvfXAZqbTuj47xgXFhPYleEl/PUq+Gj62kaOGRu/8hegf0CF8V8+LAbE1faRmMGpFgR0cbzABs9TH2M+2qkc8gyBqqKeK6+V+q2WeJqBwpWUjSC+/Qp7MOs36DL2KzB175BNXUZKQv3vJdvb9VOWuqg=,iv:efKLXxpjTSV/iJSAUfWyzyBShkcTOUDOoy/MaP3dDK8=,tag:UGEgAV1lTtihOY4EkcnKIQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
