apiVersion: ENC[AES256_GCM,data:ymA=,iv:T0dTcZ3TowNfa0yBAkVMuSZ6xM7N8xJ5WUem5BIMqZA=,tag:JDIbJrk1QsGmy7x95RbJAw==,type:str]
kind: ENC[AES256_GCM,data:T7LoazQv,iv:w1VgplCWAUMTML1QCLFB1a3TZChUj8mZxsa75vXEjm0=,tag:u6R2RqEia0ywTd7DnwNs8A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Si4kFG8v3E4t5GwvkI5bwnlVb7Q=,iv:TDF6mk54sfgsjncdl1DNv9Iy7JdVdB2idQAc6G3+xMQ=,tag:1R9DYed3kuFIoiWnF5Cv1A==,type:str]
    namespace: ENC[AES256_GCM,data:UY+zX3tG0jYNcrWZ,iv:Zvn0DS7dpeSvbeF2bYS3Hn/n73SCktEB5bJ9dS50YjU=,tag:68wCcJ8Z7u0/uIcd0hhQCA==,type:str]
type: ENC[AES256_GCM,data:9XH8xiw8,iv:jcJLPfBFUq7A05ggMz4PWyxbPClV347qm+25WT4gYZQ=,tag:6outO+6UcEEtHx/+XjwDoQ==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:n27TkrtlVoiTa+86D8xpwE2+up4vd3i8eX+mmySvshc/07o8j31j8g==,iv:5HgpPXVvYPBkTLoK5VA052vhFh1O4DRyDn9JHU5qx18=,tag:b7CoozNr3V3HUsyAKKxbXg==,type:str]
sops:
    age:
        - recipient: age1fwe5ta3ey6mzz35t9tupd9a7wpcx5zch9x886hg53vll0ev77g6st4wwc6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWjBwazRnaytOeXFWVDIy
            M3JnQXFqVlFRZnNsTTMwaS9jK1QybUJLdUVrCnVhM3c1RE8vbXNDaGtHNWhzVXFr
            c20zWEE4L3NCWUxpcnRUUDYwd2NtVEkKLS0tIGJrYkFsK050YmZPYUpQSzNGbkdx
            bkRueHVtNmM1WS81MnRCVmFTYlVxT3cK5ggUETHCDomCb1aVKK3eLQmLqDnqIhZ9
            x0Kqb+47cpYReMrMbt8I9f1l3Uf5bM+7uAjAcJjljmKr6LSLbb/DIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T17:40:20Z"
    mac: ENC[AES256_GCM,data:hTVJB0nATNu9BedQC9QkG/bCIcIZUz6tDuTOggHAsf9QuRCZamFVMDiCeNQOBvRtqM33Qg+OjK84NwWk5mzMt8Rgx5YcuPMJlxOYmlKZqrMgMHu8PKgMApfcQQkp0fu1HOTz0HlhKhvYUsLOcWtAbw9yZ6KnT+1wH2c0NTDfFzY=,iv:i2fJICeWfWiLmHrGFX9B/1SmDANQGCCczhVJfSOfTKI=,tag:itxvEYJM2sQtILQnH4D2iw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
