apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-middleware
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"  # Deploy with Traefik
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: traefik-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/jamilshaikh07/talos-proxmox-gitops.git
    targetRevision: master
    path: gitops/manifests/traefik-middleware
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false  # traefik-system already exists
