---
# Static Ansible Inventory
# Talos K8s: CP: 10.20.0.40, Workers: 10.20.0.41-43, Bare metal: 10.20.0.45

all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    # Network configuration
    network_cidr: "10.20.0.0/24"
    network_gateway: "10.20.0.1"
