apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: longhorn-critical
  annotations:
    argocd.argoproj.io/sync-wave: "1"
value: 1000000000
globalDefault: false
description: "Priority class for Longhorn system critical pods"
